version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      github-actions:
        patterns:
          - "*"
      codeql-action:
        patterns:
          - "github/codeql-action*"
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
